### ISSUE TITLE
이전버전 부터 파싱실패가 뜹니다

### ISSUE THREAD

**Issue by qprhvms** [occidere/MMDownloader#44]
주소를 입력하세요: http://marumaru.in/b/manga/147728
[Error] 2017-10-30_11-51-50_Jsoup_파싱_실패.txt
총 0개

이런식으로 파싱실패가뜨내요
다른주소를써도똑같구요

**Comment by occidere** [comment]
이제서야 봤네요...
확인해보겠습니다!

**Comment by occidere** [comment]
현재 확인 결과 정상적으로 동작하고 있습니다.
파싱 실패인 경우의 대부분은 사이트 트래픽 급증으로 인한 DDoS 보호가 동작했을 때입니다.
아마 이슈가 발생한 시점에서가 그러하지 않았을까 생각합니다.
추후 사이트의 상태를 체크할 수 있는 기능이나 보호를 우회할 수 있는 방법을 찾아볼 수 있도록 하겠습니다!

**Comment by qprhvms** [comment]
확인해주셔서 감사합니다 ^^;;
프리웨어 공유에 감사할뿐입니다
